baseurl = "https://mrkasuj.eu"
languageCode = "en"
title = "my learning notes"
theme = "kiss"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
#adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "mrkasuj"
github = "mrkasuj"
linkedin = "kamilsujecki"
facebook = "mrkasuj"
instagram = "mrkasuj"


[params.social.config]
platforms = ["github","facebook","twitter","instagram","linkedin"]

[taxonomies]
tag ="tags"
